Задання 1. Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0. 

In [2]:
import numpy as np
from time import time

In [3]:
def task_1():
    
    import numpy as np
    from time import time

    n = int(input("Введіть число n: "))

    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.zeros((n, n), dtype=int)
    np.fill_diagonal(arr_numpy, np.arange(1, n+1))
    end = time()

    print("\nМасив через NumPy:")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end-start:.8f} сек\n")

    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        arr_loops[i][i] = i + 1
    end = time()

    print("Масив через цикли:")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end-start:.8f} сек\n")

In [4]:
task_1()


Масив через NumPy:
[[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 5 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 8]]
Час виконання NumPy: 0.00000000 сек

Масив через цикли:
[1, 0, 0, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 0, 0, 0, 0, 0]
[0, 0, 0, 4, 0, 0, 0, 0]
[0, 0, 0, 0, 5, 0, 0, 0]
[0, 0, 0, 0, 0, 6, 0, 0]
[0, 0, 0, 0, 0, 0, 7, 0]
[0, 0, 0, 0, 0, 0, 0, 8]
Час виконання циклів: 0.00000000 сек



Вправа 2. Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром n×n, використовуючи слайсінг. 

In [5]:
def task_2():
   
    n = int(input("Введіть число n: "))

    # Спосіб 1: NumPy (слайсінг)
    start = time()
    arr_numpy = np.zeros((n, n), dtype=int)
    arr_numpy[::2, ::2] = 1  # Заповнення кожного другого елемента
    arr_numpy[1::2, 1::2] = 1
    end = time()

    print("\nМасив через NumPy (слайсінг):")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end-start:.8f} сек\n")

    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                arr_loops[i][j] = 1
    end = time()

    print("Масив через цикли:")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end-start:.8f} сек\n")

In [6]:
task_2()


Масив через NumPy (слайсінг):
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
Час виконання NumPy: 0.00000000 сек

Масив через цикли:
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
Час виконання циклів: 0.00000000 сек



Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [7]:
def task_3():
    # Введення чисел n, m, r, c
    n, m, r, c = map(int, input("Введіть числа n, m, r, c через пробіл: ").split())

    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.ones((n, m), dtype=int)  # Спочатку заповнюємо одиничним масивом
    arr_numpy[r, :] = 0  # Онуляємо рядок r
    arr_numpy[:, c] = 0  # Онуляємо стовпець c
    end = time()

    print("\nМасив через NumPy:")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end-start:.8f} сек\n")

    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[1 for _ in range(m)] for _ in range(n)]  # Спочатку заповнюємо одиничним масивом
    for i in range(n):
        arr_loops[i][c] = 0  # Онуляємо стовпець c
    arr_loops[r] = [0] * m  # Онуляємо рядок r
    end = time()

    print("Масив через цикли:")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end-start:.8f} сек\n")

In [8]:
task_3()


Масив через NumPy:
[[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]]
Час виконання NumPy: 0.00000000 сек

Масив через цикли:
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 1]
Час виконання циклів: 0.00000000 сек



Вправа 4. Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [9]:
def task_4():
    n, m = map(int, input("Введіть n m: ").split())

    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.zeros((n, m), dtype=int)
    arr_numpy[0] = np.arange(m)
    end = time()
    print("\nМасив через NumPy:")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end - start:.8f} сек\n")

    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[0] * m for _ in range(n)]
    for j in range(m):
        arr_loops[0][j] = j
    end = time()
    print("Масив через цикли:")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end - start:.8f} сек\n")

In [10]:
task_4()


Масив через NumPy:
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Час виконання NumPy: 0.00000000 сек

Масив через цикли:
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
Час виконання циклів: 0.00000000 сек



Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на –1. 

In [12]:
def task_6():
    # Введення масиву через пробіл
    data = list(map(int, input("Введіть елементи масиву через пробіл: ").split()))
    arr = np.array(data)
    
    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.where(arr != 0, -1, 0)
    end = time()
    print("Результат через NumPy:", arr_numpy)
    print(f"Час виконання NumPy: {end - start:.8f} сек")
    
    # Спосіб 2: Цикли
    start = time()
    arr_loops = [-1 if x != 0 else 0 for x in data]
    end = time()
    print("Результат через цикли:", arr_loops)
    print(f"Час виконання циклів: {end - start:.8f} сек")

In [13]:
task_6()

Результат через NumPy: [-1 -1  0 -1  0 -1 -1  0]
Час виконання NumPy: 0.00000000 сек
Результат через цикли: [-1, -1, 0, -1, 0, -1, -1, 0]
Час виконання циклів: 0.00000000 сек


Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [14]:
def task_8():
    # Введення масиву через пробіл
    data = list(map(int, input("Введіть елементи масиву через пробіл: ").split()))
    arr = np.array(data)
    
    # Спосіб 1: NumPy
    start = time()
    zeros = np.sum(arr == 0)
    nonzeros = np.sum(arr != 0)
    end = time()
    print(f"NumPy: нульових = {zeros}, ненульових = {nonzeros}")
    print(f"Час виконання NumPy: {end - start:.8f} сек")
    
    # Спосіб 2: Цикли
    start = time()
    zeros2 = 0
    nonzeros2 = 0
    for x in data:
        if x == 0:
            zeros2 += 1
        else:
            nonzeros2 += 1
    end = time()
    print(f"Цикли: нульових = {zeros2}, ненульових = {nonzeros2}")
    print(f"Час виконання циклів: {end - start:.8f} сек")

In [16]:
task_8()

NumPy: нульових = 1, ненульових = 2
Час виконання NumPy: 0.00000000 сек
Цикли: нульових = 1, ненульових = 2
Час виконання циклів: 0.00000000 сек


Вправа 11. Створити масив одиниць розміром n×n та додати до нього «рамку», що утворюється з 0. 

In [21]:
def task_11():
    n = int(input("Введіть число n: "))
    
    # Спосіб 1: NumPy
    start = time()
    inner = np.ones((n, n), dtype=int)
    arr_numpy = np.zeros((n + 2, n + 2), dtype=int)
    arr_numpy[1:-1, 1:-1] = inner
    end = time()
    print("Масив через NumPy:")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end - start:.8f} сек")
    
    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[0] * (n + 2) for _ in range(n + 2)]
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            arr_loops[i][j] = 1
    end = time()
    print("Масив через цикли:")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end - start:.8f} сек")

In [22]:
task_11()

Масив через NumPy:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
Час виконання NumPy: 0.00000000 сек
Масив через цикли:
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]
Час виконання циклів: 0.00000000 сек


Вправа 20. Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0. 

In [25]:
def task_20():
    # Введення числа n
    n = int(input("Введіть число n: "))

    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.random.random(n)  # Генерація випадкових елементів (0,1)
    original_numpy = arr_numpy.copy()  # Зберігаємо оригінальний вектор для порівняння
    arr_numpy[arr_numpy.argmax()] = 0  # Замінити максимальний елемент на 0
    end = time()

    print("\nОригінальний вектор через NumPy:")
    print(original_numpy)
    print("\nВектор після зміни через NumPy:")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end-start:.8f} сек\n")

    # Спосіб 2: Цикли
    start = time()
    arr_loops = [np.random.random() for _ in range(n)]  # Генерація випадкових елементів
    original_loops = arr_loops.copy()  # Зберігаємо оригінальний вектор для порівняння
    max_index = arr_loops.index(max(arr_loops))  # Пошук максимального елемента
    arr_loops[max_index] = 0  # Замінити максимальний елемент на 0
    end = time()

    print("Оригінальний вектор через цикли:")
    print(original_loops)
    print("\nВектор після зміни через цикли:")
    print(arr_loops)
    print(f"Час виконання циклів: {end-start:.8f} сек\n")

In [26]:
task_20()


Оригінальний вектор через NumPy:
[0.27503088 0.67401258 0.8141348 ]

Вектор після зміни через NumPy:
[0.27503088 0.67401258 0.        ]
Час виконання NumPy: 0.00000000 сек

Оригінальний вектор через цикли:
[0.7834972736433995, 0.3574569921540659, 0.023008994305587227]

Вектор після зміни через цикли:
[0, 0.3574569921540659, 0.023008994305587227]
Час виконання циклів: 0.00000000 сек



Вправа 21. Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком. 

In [27]:
def task_21():
    # Введення n та m
    n, m = map(int, input("Введіть числа n m: ").split())
    
    # Спосіб 1: NumPy
    start = time()
    arr_numpy = np.random.randint(0, m+1, (n, n))
    print("Оригінальна матриця через NumPy:")
    print(arr_numpy)
    max_val = arr_numpy.max()
    arr_numpy[arr_numpy == max_val] *= -1
    end = time()
    print("Матриця після зміни (NumPy):")
    print(arr_numpy)
    print(f"Час виконання NumPy: {end - start:.8f} сек")
    
    # Спосіб 2: Цикли
    start = time()
    arr_loops = [[np.random.randint(0, m+1) for _ in range(n)] for _ in range(n)]
    print("Оригінальна матриця через цикли:")
    for row in arr_loops:
        print(row)
    # Знаходимо максимальне значення
    max_val2 = max(max(row) for row in arr_loops)
    # Замінюємо всі максимальні елементи на протилежний знак
    for i in range(n):
        for j in range(n):
            if arr_loops[i][j] == max_val2:
                arr_loops[i][j] = -arr_loops[i][j]
    end = time()
    print("Матриця після зміни (цикли):")
    for row in arr_loops:
        print(row)
    print(f"Час виконання циклів: {end - start:.8f} сек")

In [28]:
task_21()

Оригінальна матриця через NumPy:
[[1 3 3]
 [0 0 4]
 [4 4 0]]
Матриця після зміни (NumPy):
[[ 1  3  3]
 [ 0  0 -4]
 [-4 -4  0]]
Час виконання NumPy: 0.00000000 сек
Оригінальна матриця через цикли:
[2, 0, 0]
[2, 3, 0]
[3, 4, 3]
Матриця після зміни (цикли):
[2, 0, 0]
[2, 3, 0]
[3, -4, 3]
Час виконання циклів: 0.00000000 сек


Розв'язати систему рівнянь:
4x1 + x2 - x4 = -9
x1 - 3x2 + 4x3 = 7
3x2 - 2x3 + 4x4 = 12
x1 + 2x3 + 4x4 = 12

Трьома способами:
- формули Крамера,
- обернена матриця,
- numpy.linalg.solve()

Перевірка через numpy.allclose()

In [29]:
from numpy.linalg import det, inv, solve
def solve_system():
    # Коефіцієнтна матриця та вектор вільних членів
    A = np.array([[4, 1, 0, -1],
                  [1, -3, 4, 0],
                  [0, 3, -2, 4],
                  [1, 0, 2, 4]], dtype=float)
    b = np.array([-9, 7, 12, 12], dtype=float)

    # Формули Крамера
    detA = det(A)
    x_cramer = np.zeros(4)
    for i in range(4):
        Ai = A.copy()
        Ai[:, i] = b
        x_cramer[i] = det(Ai) / detA

    # Обернена матриця
    A_inv = inv(A)
    x_inv = A_inv.dot(b)

    # numpy.linalg.solve
    x_solve = solve(A, b)

    # Вивід результатів
    print("Рішення системи рівнянь:")
    print("Метод Крамера:", x_cramer)
    print("Через обернену матрицю:", x_inv)
    print("numpy.linalg.solve():", x_solve)
    # Перевірка
    print("Перевірка рівності рішень (allclose):", np.allclose(x_cramer, x_inv) and np.allclose(x_inv, x_solve))

In [30]:
solve_system()

Рішення системи рівнянь:
Метод Крамера: [-7.88129935e+15  2.36438980e+16  1.97032484e+16 -7.88129935e+15]
Через обернену матрицю: [-7.88129935e+15  2.36438980e+16  1.97032484e+16 -7.88129935e+15]
numpy.linalg.solve(): [-7.88129935e+15  2.36438980e+16  1.97032484e+16 -7.88129935e+15]
Перевірка рівності рішень (allclose): True


Обчислити вираз: 3(A^2 - B^2) - 2AB, де A і B - задані матриці.

In [31]:
def task_3_matrix_expression():
    # Задано матриці A та B
    A = np.array([[4, 2, 1], [3, -2, 0], [1, 0, 2]])
    B = np.array([[2, 0, 2], [5, -7, -2], [1, 0, -1]])

    # Спосіб 1: NumPy (Універсальні функції)
    start = time()
    A_squared = np.dot(A, A)  # A^2
    B_squared = np.dot(B, B)  # B^2
    AB = np.dot(A, B)         # AB
    result_numpy = 3 * (A_squared - B_squared) - 2 * AB  # 3(A^2 - B^2) - 2AB
    end = time()

    print("\nМатричний вираз через NumPy:")
    print(result_numpy)
    print(f"Час виконання NumPy: {end-start:.8f} сек\n")

    # Спосіб 2: Цикли (поелементне обчислення)
    start = time()
    A_squared_loops = np.array([[sum(A[i, k] * A[k, j] for k in range(3)) for j in range(3)] for i in range(3)])  # A^2 через цикли
    B_squared_loops = np.array([[sum(B[i, k] * B[k, j] for k in range(3)) for j in range(3)] for i in range(3)])  # B^2 через цикли
    AB_loops = np.array([[sum(A[i, k] * B[k, j] for k in range(3)) for j in range(3)] for i in range(3)])  # AB через цикли
    result_loops = 3 * (A_squared_loops - B_squared_loops) - 2 * AB_loops  # 3(A^2 - B^2) - 2AB через цикли
    end = time()

    print("Матричний вираз через цикли:")
    print(result_loops)
    print(f"Час виконання циклів: {end-start:.8f} сек\n")

    # Перевірка результатів через np.allclose()
    print("Перевірка результатів через np.allclose():")
    print(np.allclose(result_numpy, result_loops))

In [32]:
task_3_matrix_expression()


Матричний вираз через NumPy:
[[  13   40    6]
 [ 107 -145  -89]
 [   7    6    6]]
Час виконання NumPy: 0.00000000 сек

Матричний вираз через цикли:
[[  13   40    6]
 [ 107 -145  -89]
 [   7    6    6]]
Час виконання циклів: 0.00000000 сек

Перевірка результатів через np.allclose():
True
